require "bundler/setup"
require "indie_bookstore_finder"
require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require_relative "../lib/indie_bookstore_finder/city"
require_relative "../lib/indie_bookstore_finder/CLI"
require_relative "../lib/indie_bookstore_finder/scraper"
require_relative "../lib/indie_bookstore_finder/state"
require_relative "../lib/indie_bookstore_finder/store"
